"""empty message

Revision ID: 235dc8706696
Revises: 
Create Date: 2022-03-19 20:03:29.853721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235dc8706696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('num_bedrooms', sa.Integer(), nullable=True),
    sa.Column('num_bathrooms', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=400), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('imagePath', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
