"""empty message

Revision ID: 6decc57d5252
Revises: 235dc8706696
Create Date: 2022-03-19 23:16:15.035684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6decc57d5252'
down_revision = '235dc8706696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('type', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'type')
    # ### end Alembic commands ###
